### ISSUE TITLE
Integrate Disqus

### ISSUE THREAD

**Issue by palcu** [infoeducatie/blog.infoeducatie.ro#4]
We need interactivity.

**Comment by robertdxyz** [comment]
https://help.disqus.com/customer/portal/articles/472138-jekyll-installation-instructions

**Comment by robertdxyz** [comment]
This is interesting http://eviltrout.com/2014/01/22/embedding-discourse.html
I am experimenting with it

**Comment by robertdxyz** [comment]
Discourse integrated

**Comment by hurrycane** [comment]
Great job!
